// Generated by the Supabase MCP `generate_typescript_types` tool against
// project hgkjlyggzrziylwazadc. Regenerate after schema changes:
//   npx supabase gen types typescript --project-id hgkjlyggzrziylwazadc --schema public
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_settings: {
        Row: {
          center_lat: number
          center_lng: number
          city: string
          id: number
          model: string
          ollama_url: string
          tz: string
          updated_at: string
        }
        Insert: {
          center_lat: number
          center_lng: number
          city: string
          id?: number
          model?: string
          ollama_url?: string
          tz: string
          updated_at?: string
        }
        Update: {
          center_lat?: number
          center_lng?: number
          city?: string
          id?: number
          model?: string
          ollama_url?: string
          tz?: string
          updated_at?: string
        }
        Relationships: []
      }
      calendar_entries: {
        Row: {
          added_at: string
          event_id: string
          google_event_id: string | null
          user_id: string
        }
        Insert: {
          added_at?: string
          event_id: string
          google_event_id?: string | null
          user_id: string
        }
        Update: {
          added_at?: string
          event_id?: string
          google_event_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "calendar_entries_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_entries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          address: string | null
          category: Database["public"]["Enums"]["event_category"]
          created_at: string
          dedupe_key: string
          description: string
          ends_at: string
          id: string
          is_free: boolean
          lat: number
          lng: number
          price: string
          promoted: boolean
          rarity: Database["public"]["Enums"]["event_rarity"]
          rating: number
          rating_rationale: string | null
          recurrence: string | null
          source_id: string
          source_kind: Database["public"]["Enums"]["event_source_kind"]
          starts_at: string
          tags: string[]
          ticket_provider: string | null
          ticket_url: string | null
          title: string
          updated_at: string
          venue: string
        }
        Insert: {
          address?: string | null
          category: Database["public"]["Enums"]["event_category"]
          created_at?: string
          dedupe_key: string
          description?: string
          ends_at: string
          id: string
          is_free?: boolean
          lat: number
          lng: number
          price?: string
          promoted?: boolean
          rarity?: Database["public"]["Enums"]["event_rarity"]
          rating?: number
          rating_rationale?: string | null
          recurrence?: string | null
          source_id: string
          source_kind?: Database["public"]["Enums"]["event_source_kind"]
          starts_at: string
          tags?: string[]
          ticket_provider?: string | null
          ticket_url?: string | null
          title: string
          updated_at?: string
          venue: string
        }
        Update: {
          address?: string | null
          category?: Database["public"]["Enums"]["event_category"]
          created_at?: string
          dedupe_key?: string
          description?: string
          ends_at?: string
          id?: string
          is_free?: boolean
          lat?: number
          lng?: number
          price?: string
          promoted?: boolean
          rarity?: Database["public"]["Enums"]["event_rarity"]
          rating?: number
          rating_rationale?: string | null
          recurrence?: string | null
          source_id?: string
          source_kind?: Database["public"]["Enums"]["event_source_kind"]
          starts_at?: string
          tags?: string[]
          ticket_provider?: string | null
          ticket_url?: string | null
          title?: string
          updated_at?: string
          venue?: string
        }
        Relationships: [
          {
            foreignKeyName: "events_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      geocode_cache: {
        Row: {
          created_at: string
          lat: number | null
          lng: number | null
          name: string
          query: string
        }
        Insert: {
          created_at?: string
          lat?: number | null
          lng?: number | null
          name?: string
          query: string
        }
        Update: {
          created_at?: string
          lat?: number | null
          lng?: number | null
          name?: string
          query?: string
        }
        Relationships: []
      }
      ingests: {
        Row: {
          added: number
          events: Json
          extracted: number
          id: string
          kind: Database["public"]["Enums"]["ingest_kind"]
          received_at: string
          source: string
          subject: string | null
        }
        Insert: {
          added?: number
          events?: Json
          extracted?: number
          id?: string
          kind: Database["public"]["Enums"]["ingest_kind"]
          received_at?: string
          source: string
          subject?: string | null
        }
        Update: {
          added?: number
          events?: Json
          extracted?: number
          id?: string
          kind?: Database["public"]["Enums"]["ingest_kind"]
          received_at?: string
          source?: string
          subject?: string | null
        }
        Relationships: []
      }
      raw_emails: {
        Row: {
          body_text: string
          char_count: number | null
          email_key: string
          error: string | null
          from_addr: string
          id: string
          ingest_id: string | null
          processed_at: string | null
          received_at: string
          source: string
          subject: string
          to_addr: string
        }
        Insert: {
          body_text?: string
          char_count?: number | null
          email_key: string
          error?: string | null
          from_addr?: string
          id?: string
          ingest_id?: string | null
          processed_at?: string | null
          received_at?: string
          source: string
          subject?: string
          to_addr?: string
        }
        Update: {
          body_text?: string
          char_count?: number | null
          email_key?: string
          error?: string | null
          from_addr?: string
          id?: string
          ingest_id?: string | null
          processed_at?: string | null
          received_at?: string
          source?: string
          subject?: string
          to_addr?: string
        }
        Relationships: [
          {
            foreignKeyName: "raw_emails_ingest_id_fkey"
            columns: ["ingest_id"]
            isOneToOne: false
            referencedRelation: "ingests"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          created_at: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Insert: {
          created_at?: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Update: {
          created_at?: string
          expires_at?: string
          token_hash?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          active: boolean
          address: string
          created_at: string
          id: string
          kind: string
          name: string
          note: string
        }
        Insert: {
          active?: boolean
          address?: string
          created_at?: string
          id: string
          kind?: string
          name: string
          note?: string
        }
        Update: {
          active?: boolean
          address?: string
          created_at?: string
          id?: string
          kind?: string
          name?: string
          note?: string
        }
        Relationships: []
      }
      user_google_tokens: {
        Row: {
          access_token: string
          expires_at: string
          refresh_token: string
          scope: string
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token: string
          expires_at: string
          refresh_token: string
          scope?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token?: string
          expires_at?: string
          refresh_token?: string
          scope?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_google_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          email: string
          feed_token: string | null
          google_id: string
          id: string
          last_login_at: string
          name: string
          picture: string
          prefs: Json
        }
        Insert: {
          created_at?: string
          email: string
          feed_token?: string | null
          google_id: string
          id?: string
          last_login_at?: string
          name?: string
          picture?: string
          prefs?: Json
        }
        Update: {
          created_at?: string
          email?: string
          feed_token?: string | null
          google_id?: string
          id?: string
          last_login_at?: string
          name?: string
          picture?: string
          prefs?: Json
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      event_category:
        | "music"
        | "food"
        | "sports"
        | "arts"
        | "market"
        | "festival"
        | "community"
      event_rarity: "common" | "notable" | "rare"
      event_source_kind: "seed" | "newsletter" | "manual"
      ingest_kind: "email" | "manual"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      event_category: [
        "music",
        "food",
        "sports",
        "arts",
        "market",
        "festival",
        "community",
      ],
      event_rarity: ["common", "notable", "rare"],
      event_source_kind: ["seed", "newsletter", "manual"],
      ingest_kind: ["email", "manual"],
    },
  },
} as const
