// Generated by the Supabase MCP `generate_typescript_types` tool against
// the Supabase project. Regenerate after schema changes:
//   npx supabase gen types typescript --project-id <your-project-id> --schema public
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_settings: {
        Row: {
          center_lat: number
          center_lng: number
          chat_provider: string
          city: string
          extract_provider: string
          id: number
          model: string
          ollama_url: string
          tz: string
          updated_at: string
        }
        Insert: {
          center_lat: number
          center_lng: number
          chat_provider?: string
          city: string
          extract_provider?: string
          id?: number
          model?: string
          ollama_url?: string
          tz: string
          updated_at?: string
        }
        Update: {
          center_lat?: number
          center_lng?: number
          chat_provider?: string
          city?: string
          extract_provider?: string
          id?: number
          model?: string
          ollama_url?: string
          tz?: string
          updated_at?: string
        }
        Relationships: []
      }
      calendar_entries: {
        Row: {
          added_at: string
          event_id: string
          google_event_id: string | null
          user_id: string
        }
        Insert: {
          added_at?: string
          event_id: string
          google_event_id?: string | null
          user_id: string
        }
        Update: {
          added_at?: string
          event_id?: string
          google_event_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "calendar_entries_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_entries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_messages: {
        Row: {
          content: string
          created_at: string
          id: number
          role: string
          thread_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id?: never
          role: string
          thread_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: never
          role?: string
          thread_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "chat_threads"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_threads: {
        Row: {
          created_at: string
          id: string
          provider: string
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id: string
          provider?: string
          title?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          provider?: string
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_threads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      event_reactions: {
        Row: {
          created_at: string
          event_id: string
          reaction: Database["public"]["Enums"]["event_reaction"]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          reaction: Database["public"]["Enums"]["event_reaction"]
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          reaction?: Database["public"]["Enums"]["event_reaction"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_reactions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          address: string | null
          category: Database["public"]["Enums"]["event_category"]
          created_at: string
          dedupe_key: string
          description: string
          ends_at: string
          id: string
          image_color: string | null
          image_url: string | null
          is_free: boolean
          lat: number
          lng: number
          price: string
          promoted: boolean
          rarity: Database["public"]["Enums"]["event_rarity"]
          rating: number
          rating_rationale: string | null
          recurrence: string | null
          source_id: string
          source_kind: Database["public"]["Enums"]["event_source_kind"]
          starts_at: string
          tags: string[]
          ticket_provider: string | null
          ticket_url: string | null
          title: string
          updated_at: string
          venue: string
        }
        Insert: {
          address?: string | null
          category: Database["public"]["Enums"]["event_category"]
          created_at?: string
          dedupe_key: string
          description?: string
          ends_at: string
          id: string
          image_color?: string | null
          image_url?: string | null
          is_free?: boolean
          lat: number
          lng: number
          price?: string
          promoted?: boolean
          rarity?: Database["public"]["Enums"]["event_rarity"]
          rating?: number
          rating_rationale?: string | null
          recurrence?: string | null
          source_id: string
          source_kind?: Database["public"]["Enums"]["event_source_kind"]
          starts_at: string
          tags?: string[]
          ticket_provider?: string | null
          ticket_url?: string | null
          title: string
          updated_at?: string
          venue: string
        }
        Update: {
          address?: string | null
          category?: Database["public"]["Enums"]["event_category"]
          created_at?: string
          dedupe_key?: string
          description?: string
          ends_at?: string
          id?: string
          image_color?: string | null
          image_url?: string | null
          is_free?: boolean
          lat?: number
          lng?: number
          price?: string
          promoted?: boolean
          rarity?: Database["public"]["Enums"]["event_rarity"]
          rating?: number
          rating_rationale?: string | null
          recurrence?: string | null
          source_id?: string
          source_kind?: Database["public"]["Enums"]["event_source_kind"]
          starts_at?: string
          tags?: string[]
          ticket_provider?: string | null
          ticket_url?: string | null
          title?: string
          updated_at?: string
          venue?: string
        }
        Relationships: [
          {
            foreignKeyName: "events_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      geocode_cache: {
        Row: {
          created_at: string
          lat: number | null
          lng: number | null
          name: string
          query: string
        }
        Insert: {
          created_at?: string
          lat?: number | null
          lng?: number | null
          name?: string
          query: string
        }
        Update: {
          created_at?: string
          lat?: number | null
          lng?: number | null
          name?: string
          query?: string
        }
        Relationships: []
      }
      ingests: {
        Row: {
          added: number
          events: Json
          extracted: number
          id: string
          kind: Database["public"]["Enums"]["ingest_kind"]
          received_at: string
          source: string
          subject: string | null
        }
        Insert: {
          added?: number
          events?: Json
          extracted?: number
          id?: string
          kind: Database["public"]["Enums"]["ingest_kind"]
          received_at?: string
          source: string
          subject?: string | null
        }
        Update: {
          added?: number
          events?: Json
          extracted?: number
          id?: string
          kind?: Database["public"]["Enums"]["ingest_kind"]
          received_at?: string
          source?: string
          subject?: string | null
        }
        Relationships: []
      }
      push_keys: {
        Row: {
          created_at: string
          id: number
          private_key: string
          public_key: string
        }
        Insert: {
          created_at?: string
          id?: number
          private_key: string
          public_key: string
        }
        Update: {
          created_at?: string
          id?: number
          private_key?: string
          public_key?: string
        }
        Relationships: []
      }
      push_sends: {
        Row: {
          key: string
          sent_at: string
        }
        Insert: {
          key: string
          sent_at?: string
        }
        Update: {
          key?: string
          sent_at?: string
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          leave_by: boolean
          p256dh: string
          reminders: boolean
          user_id: string
          weekly_digest: boolean
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          leave_by?: boolean
          p256dh: string
          reminders?: boolean
          user_id: string
          weekly_digest?: boolean
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          leave_by?: boolean
          p256dh?: string
          reminders?: boolean
          user_id?: string
          weekly_digest?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      raw_emails: {
        Row: {
          body_text: string
          char_count: number | null
          email_key: string
          error: string | null
          from_addr: string
          id: string
          ingest_id: string | null
          processed_at: string | null
          received_at: string
          source: string
          subject: string
          to_addr: string
        }
        Insert: {
          body_text?: string
          char_count?: number | null
          email_key: string
          error?: string | null
          from_addr?: string
          id?: string
          ingest_id?: string | null
          processed_at?: string | null
          received_at?: string
          source: string
          subject?: string
          to_addr?: string
        }
        Update: {
          body_text?: string
          char_count?: number | null
          email_key?: string
          error?: string | null
          from_addr?: string
          id?: string
          ingest_id?: string | null
          processed_at?: string | null
          received_at?: string
          source?: string
          subject?: string
          to_addr?: string
        }
        Relationships: [
          {
            foreignKeyName: "raw_emails_ingest_id_fkey"
            columns: ["ingest_id"]
            isOneToOne: false
            referencedRelation: "ingests"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          active: boolean
          address: string
          created_at: string
          id: string
          kind: string
          name: string
          note: string
        }
        Insert: {
          active?: boolean
          address?: string
          created_at?: string
          id: string
          kind?: string
          name: string
          note?: string
        }
        Update: {
          active?: boolean
          address?: string
          created_at?: string
          id?: string
          kind?: string
          name?: string
          note?: string
        }
        Relationships: []
      }
      user_google_calendar: {
        Row: {
          scope: string
          secret_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          scope?: string
          secret_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          scope?: string
          secret_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_google_calendar_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          email: string
          feed_token: string | null
          id: string
          last_lat: number | null
          last_lng: number | null
          last_login_at: string
          last_pos_at: string | null
          name: string
          picture: string
          prefs: Json
        }
        Insert: {
          created_at?: string
          email: string
          feed_token?: string | null
          id: string
          last_lat?: number | null
          last_lng?: number | null
          last_login_at?: string
          last_pos_at?: string | null
          name?: string
          picture?: string
          prefs?: Json
        }
        Update: {
          created_at?: string
          email?: string
          feed_token?: string | null
          id?: string
          last_lat?: number | null
          last_lng?: number | null
          last_login_at?: string
          last_pos_at?: string | null
          name?: string
          picture?: string
          prefs?: Json
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      google_calendar_clear: { Args: { p_user_id: string }; Returns: undefined }
      google_calendar_get: {
        Args: { p_user_id: string }
        Returns: {
          refresh_token: string
          scope: string
        }[]
      }
      google_calendar_set: {
        Args: { p_refresh_token: string; p_scope?: string; p_user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      event_category:
        | "music"
        | "food"
        | "sports"
        | "arts"
        | "market"
        | "festival"
        | "community"
      event_rarity: "common" | "notable" | "rare"
      event_reaction: "going" | "went" | "not_for_me"
      event_source_kind: "seed" | "newsletter" | "manual"
      ingest_kind: "email" | "manual"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      event_category: [
        "music",
        "food",
        "sports",
        "arts",
        "market",
        "festival",
        "community",
      ],
      event_rarity: ["common", "notable", "rare"],
      event_reaction: ["going", "went", "not_for_me"],
      event_source_kind: ["seed", "newsletter", "manual"],
      ingest_kind: ["email", "manual"],
    },
  },
} as const
