/**
 * Regenerate src/db-types.ts from the Supabase project the server points at.
 *
 * The project ref is taken from SUPABASE_URL in server/.env, so it never has to
 * be written into the repo. The Supabase CLI does the generation and needs to be
 * signed in: `supabase login` once, or SUPABASE_ACCESS_TOKEN in the environment.
 *
 *   npm run db:types
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (rel) => fileURLToPath(new URL(rel, import.meta.url));

function envValue(key) {
  if (process.env[key]) return process.env[key];
  let text = "";
  try {
    text = readFileSync(here("../.env"), "utf8");
  } catch {
    return undefined;
  }
  const line = text.split(/\r?\n/).find((l) => l.startsWith(`${key}=`));
  return line?.slice(key.length + 1).trim().replace(/^["']|["']$/g, "");
}

const url = envValue("SUPABASE_URL");
const ref = url?.match(/^https:\/\/([a-z0-9]+)\.supabase\.co/)?.[1];
if (!ref) {
  console.error("SUPABASE_URL is not set (server/.env) or is not a *.supabase.co URL");
  process.exit(1);
}

let types;
try {
  types = execFileSync(
    "npx",
    ["supabase", "gen", "types", "typescript", "--project-id", ref, "--schema", "public"],
    { encoding: "utf8", shell: process.platform === "win32", stdio: ["ignore", "pipe", "inherit"] },
  );
} catch (err) {
  console.error(String(err.stdout ?? err.message).slice(0, 400));
  console.error("\nThe Supabase CLI could not generate types. Run `supabase login` once, or set SUPABASE_ACCESS_TOKEN.");
  process.exit(1);
}
if (!types.startsWith("export type Json")) {
  console.error(types.slice(0, 400));
  process.exit(1);
}

const header =
  "// Generated by `npm run db:types` (scripts/db-types.mjs) from the linked\n" +
  "// Supabase project. Do not edit by hand: change a migration and regenerate.\n";
writeFileSync(here("../src/db-types.ts"), header + types);
console.log(`wrote src/db-types.ts for project ${ref} (${types.split("\n").length} lines)`);
